version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: api_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "password123"
      MYSQL_DATABASE: tickets_incidents
      MYSQL_USER: api_user     
      MYSQL_PASSWORD: "ApiPass123"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:  
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    container_name: api_backend
    build: ./backend 
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy  
    environment: 
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: api_user      
      DB_PASSWORD: "ApiPass123"
      DB_NAME: tickets_incidents
    restart: unless-stopped
    networks:
      - app-network

  frontend:
    container_name: api_frontend
    build: ./frontend 
    ports:
      - "8080:80"
    networks:
        - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge